### ISSUE TITLE
Connection refused in make_request_for_tile()

### ISSUE THREAD

**Issue by mbgg** [federicomenaquintero/lamaperia#9]
I tried the example for the impatient, but it did not work:

mbrugger@linux-gy6r:~/src/lamaperia> python3.4 lamaperia.py --config ../mymap.json --format pdf --output mymap.pdf
Map bounds: 19.436536424041197 -96.95189490868657 19.52067487272485 -96.8308828690912
Downloading 108 tiles...
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, *_httplib_request_kw)
  File "/usr/lib64/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, *_extra_kw)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, *_httplib_request_kw)
  File "/usr/lib64/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, *_extra_kw)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lamaperia.py", line 71, in <module>
    main ()
  File "lamaperia.py", line 68, in main
    paper_renderer.render (args.format, args.output, chart_renderer)
  File "/home/mbrugger/src/lamaperia/paperrenderer.py", line 27, in render
    chart_renderer.render_to_cairo (cr)
  File "/home/mbrugger/src/lamaperia/chartrenderer.py", line 28, in render_to_cairo
    self.render_map_data (cr)
  File "/home/mbrugger/src/lamaperia/chartrenderer.py", line 99, in render_map_data
    self.make_map_surface (cr)
  File "/home/mbrugger/src/lamaperia/chartrenderer.py", line 78, in make_map_surface
    png_data = provider.get_tile_png (self.map_layout.zoom, tile_x, tile_y)
  File "/home/mbrugger/src/lamaperia/tile_provider.py", line 52, in get_tile_png
    r = self.make_request_for_tile (z, x, y)
  File "/home/mbrugger/src/lamaperia/tile_provider.py", line 38, in make_request_for_tile
    r = requests.get (url)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/api.py", line 68, in get
    return request('get', url, *_kwargs)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/sessions.py", line 464, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

**Comment by federicomenaquintero** [comment]
Yes, unfortunately it doesn't work out of the box right now - due to some stupidity on my part :)

I'm merging this pull request so it will work: https://github.com/federicomenaquintero/lamaperia/pull/6

In the meantime, what you can do is edit tile_provider.py and remove the line that contains "127.0.0.1".  This will make La Mapería connect directly to Mapbox instead of trying to use a local TileStache server.  Please do not get discouraged!  This will be fixed ASAP.

**Comment by mbgg** [comment]
Ok, I now get the error:
Traceback (most recent call last):
  File "lamaperia.py", line 71, in <module>
    main ()
  File "lamaperia.py", line 68, in main
    paper_renderer.render (args.format, args.output, chart_renderer)
  File "/home/mbrugger/src/lamaperia/paperrenderer.py", line 27, in render
    chart_renderer.render_to_cairo (cr)
  File "/home/mbrugger/src/lamaperia/chartrenderer.py", line 28, in render_to_cairo
    self.render_map_data (cr)
  File "/home/mbrugger/src/lamaperia/chartrenderer.py", line 99, in render_map_data
    self.make_map_surface (cr)
  File "/home/mbrugger/src/lamaperia/chartrenderer.py", line 78, in make_map_surface
    png_data = provider.get_tile_png (self.map_layout.zoom, tile_x, tile_y)
  File "/home/mbrugger/src/lamaperia/tile_provider.py", line 50, in get_tile_png
    r = self.make_request_for_tile (z, x, y)
  File "/home/mbrugger/src/lamaperia/tile_provider.py", line 45, in make_request_for_tile
    r.raise_for_status ()
  File "/usr/lib/python3.4/site-packages/requests-2.6.0-py3.4.egg/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized

I tried with my username and access_token but that didn't help neither. Might it be, that the style_id is out of date?

**Comment by federicomenaquintero** [comment]
The README.md now has a better description of how to get La Mapería configured the first time.  Unfortunately, I've just discovered that the Mapbox style requires changes to make it usable for other people.  I'll open an issue for this.

**Comment by federicomenaquintero** [comment]
Please see https://github.com/federicomenaquintero/lamaperia/issues/10 :(

**Comment by federicomenaquintero** [comment]
The configuration wizard now uses Mapbox access parameters that work!  Please update, delete your ~/.config/lamaperia and try again! :)

**Comment by mbgg** [comment]
That worked. Thanks a lot.
